# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("CUSTOMER", "Customer")],
                default="CUSTOMER",
                max_length=20,
            ),
        ),
    ]
